### ISSUE TITLE
Weber doesn't compile with elixir 0.11

### ISSUE THREAD

**Issue by Nicd** [elixir-web/weber#89]
Weber compile fails with the following stack trace (I tried to compile it as a dependency with `mix deps.get`):

```
* Compiling weber
Compiled lib/weber.ex
Compiled lib/mix/tasks/weber.ex
Compiled lib/weber/controller.ex
Compiled lib/weber/controller/layout.ex
Compiled lib/weber/cowboy.ex
Compiled lib/weber/handler/weber404_handler.ex
Compiled lib/weber/app.ex
Compiled lib/weber/handler/weber_req_handler_response.ex
Compiled lib/weber/helper/content_for_layout_helper.ex
Compiled lib/weber/handler/weber_websocket_handler.ex
Compiled lib/weber/helper/html_helper.ex
Compiled lib/weber/helper/include_view_helper.ex
Compiled lib/weber/http/cookie.ex
Compiled lib/weber/helper/resource_helper.ex
Compiled lib/weber/http/url.ex
Compiled lib/weber/http/params.ex
Compiled lib/weber/i18n/localization/locale.ex
Compiled lib/weber/i18n/localization_manager.ex
== Compilation error on file lib/weber/route.ex ==
could not compile dependency weber, mix compile failed. If you want to recompile this dependency, please run: mix deps.compile weber
** (CompileError) deps/weber/lib/weber/route.ex:34: function binary_to_atom/2 undefined
    lists.erl:1323: :lists.foreach/2
    src/elixir_lexical.erl:18: :elixir_lexical.run/2
    /home/nicd/elixir/lib/elixir/lib/kernel/parallel_compiler.ex:77: Kernel.ParallelCompiler."-spawn_compilers/8-fun-0-"/3
```
